SELECT [Nombre Entidad]
      ,[Nit Entidad]
      ,[Departamento]
      ,[Ciudad]
      ,[Localización]
      ,[Orden]
      ,[Sector]
      ,[Rama]
      ,[Entidad Centralizada]
      ,[Proceso de Compra]
      ,[ID Contrato]
      ,[Referencia del Contrato]
      ,[Estado Contrato]
      ,[Codigo de Categoria Principal]
      ,[Descripcion del Proceso]
      ,[Tipo de Contrato]
      ,[Modalidad de Contratacion]
      ,[Justificacion Modalidad de Contratacion]
      ,[Fecha de Firma]
      ,[Fecha de Inicio del Contrato]
      ,[Fecha de Fin del Contrato]
      ,[Fecha de Inicio de Ejecucion]
      ,[Fecha de Fin de Ejecucion]
      ,[Condiciones de Entrega]
      ,[TipoDocProveedor]
      ,[Documento Proveedor]
      ,[Proveedor Adjudicado]
      ,[Es Grupo]
      ,[Es Pyme]
      ,[Habilita Pago Adelantado]
      ,[Liquidación]
      ,[Obligación Ambiental]
      ,[Obligaciones Postconsumo]
      ,[Reversion]
      ,[Origen de los Recursos]
      ,[Destino Gasto]
      ,[Valor del Contrato]
      ,[Código BPIN]
      ,[Anno BPIN]
      ,[Saldo CDP]
      ,[Saldo Vigencia]
      ,[EsPostConflicto]
      ,[URLProceso]
      ,[Nombre Representante Legal]
      ,[Nacionalidad Representante Legal]
      ,[Domicilio Representante Legal]
      ,[Tipo de Identificación Representante Legal]
      ,[Identificación Representante Legal]
      ,[Género Representante Legal]
      ,[Presupuesto General de la Nacion – PGN]
      ,[Codigo Entidad]
      ,[Codigo Proveedor]
      ,[Fecha Inicio Liquidacion]
      ,[Fecha Fin Liquidacion]
      ,[Objeto Contrato]
      ,[Duracion_del_contrato]

FROM [BodegaCCE].[OpenData].[SECOPII_Contratos_completa]
WHERE [Fecha de Inicio del Contrato] IS NOT NULL
  AND RIGHT([Fecha de Firma], 4) IN ('2020', '2021', '2022', '2023', '2024', '2025')
  AND [Justificacion Modalidad de Contratacion] <> 'Servicios profesionales y apoyo a la gestión'
  AND [Objeto Contrato] not like '%Servicios profesionales%'
  AND [Objeto Contrato] not like '%Servicios personales%'
  AND [Objeto Contrato] not like '%Servicios apoyo%'